import type { Monaco } from '@monaco-editor/react';

/** Monaco theme — VS Code Dark+ token colors on Nebulla shell background. */
export const NEBULLA_MONACO_THEME = 'nebulla-dark';

/** Industry coding stack (JetBrains Mono via Bunny Fonts, then system monos). */
export const NEBULLA_CODE_FONT =
  '"JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace';

export function registerNebullaMonacoTheme(monaco: Monaco): void {
  monaco.editor.defineTheme(NEBULLA_MONACO_THEME, {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: '', foreground: 'D4D4D4' },
      { token: 'comment', foreground: '6A9955', fontStyle: 'italic' },
      { token: 'comment.doc', foreground: '6A9955', fontStyle: 'italic' },
      { token: 'string', foreground: 'CE9178' },
      { token: 'string.escape', foreground: 'D7BA7D' },
      { token: 'number', foreground: 'B5CEA8' },
      { token: 'regexp', foreground: 'D16969' },
      { token: 'keyword', foreground: '569CD6' },
      { token: 'keyword.control', foreground: 'C586C0' },
      { token: 'storage', foreground: '569CD6' },
      { token: 'storage.type', foreground: '569CD6' },
      { token: 'type', foreground: '4EC9B0' },
      { token: 'type.identifier', foreground: '4EC9B0' },
      { token: 'class', foreground: '4EC9B0' },
      { token: 'class.name', foreground: '4EC9B0' },
      { token: 'interface', foreground: '4EC9B0' },
      { token: 'enum', foreground: '4EC9B0' },
      { token: 'struct', foreground: '4EC9B0' },
      { token: 'namespace', foreground: '4EC9B0' },
      { token: 'type.parameter', foreground: '4EC9B0' },
      { token: 'function', foreground: 'DCDCAA' },
      { token: 'member', foreground: 'DCDCAA' },
      { token: 'method', foreground: 'DCDCAA' },
      { token: 'variable', foreground: '9CDCFE' },
      { token: 'variable.predefined', foreground: '4FC1FF' },
      { token: 'variable.parameter', foreground: '9CDCFE' },
      { token: 'constant', foreground: '4FC1FF' },
      { token: 'constant.language', foreground: '569CD6' },
      { token: 'constant.numeric', foreground: 'B5CEA8' },
      { token: 'attribute', foreground: '9CDCFE' },
      { token: 'attribute.name', foreground: '9CDCFE' },
      { token: 'attribute.value', foreground: 'CE9178' },
      { token: 'tag', foreground: '569CD6' },
      { token: 'tag.id', foreground: '4EC9B0' },
      { token: 'tag.class', foreground: '4EC9B0' },
      { token: 'metatag', foreground: '569CD6' },
      { token: 'metatag.content', foreground: 'CE9178' },
      { token: 'metatag.html', foreground: '569CD6' },
      { token: 'metatag.xml', foreground: '569CD6' },
      { token: 'metatag.php', foreground: '569CD6' },
      { token: 'delimiter', foreground: 'D4D4D4' },
      { token: 'delimiter.html', foreground: '808080' },
      { token: 'delimiter.xml', foreground: '808080' },
      { token: 'operator', foreground: 'D4D4D4' },
      { token: 'punctuation', foreground: 'D4D4D4' },
      { token: 'invalid', foreground: 'F44747' },
    ],
    colors: {
      'editor.background': '#141414',
      'editor.foreground': '#D4D4D4',
      'editorLineNumber.foreground': '#858585',
      'editorLineNumber.activeForeground': '#C6C6C6',
      'editor.selectionBackground': '#264F78',
      'editor.inactiveSelectionBackground': '#3A3D41',
      'editor.selectionHighlightBackground': '#ADD6FF26',
      'editor.lineHighlightBackground': '#FFFFFF0A',
      'editorCursor.foreground': '#AEAFAD',
      'editorWhitespace.foreground': '#3B3A32',
      'editorIndentGuide.background1': '#404040',
      'editorIndentGuide.activeBackground1': '#707070',
      'editorGutter.background': '#141414',
      'editorWidget.background': '#1E1E1E',
      'editorWidget.border': '#454545',
      'editorSuggestWidget.background': '#1E1E1E',
      'editorSuggestWidget.border': '#454545',
      'editorSuggestWidget.selectedBackground': '#094771',
      'editorHoverWidget.background': '#1E1E1E',
      'editorHoverWidget.border': '#454545',
      'scrollbarSlider.background': '#79797966',
      'scrollbarSlider.hoverBackground': '#646464B3',
      'scrollbarSlider.activeBackground': '#BFBFBF66',
      'editorBracketMatch.background': '#0064001A',
      'editorBracketMatch.border': '#888888',
      'editor.findMatchBackground': '#515C6A',
      'editor.findMatchHighlightBackground': '#EA5C0055',
    },
  });
}
