/**
 * Vision-assisted Resource Profile draft from a preview image.
 * Schema-strict JSON → drafts/ only (never auto-publishes).
 *
 *   npx tsx scripts/classify-ui-resource-preview.ts ./preview.png
 *   npx tsx scripts/classify-ui-resource-preview.ts ./preview.png --fixture
 *
 * Without API key or with --fixture, writes a deterministic stub draft for pipeline testing.
 */
import fs from "fs";
import path from "path";

const imgPath = process.argv[2];
const forceFixture = process.argv.includes("--fixture");
if (!imgPath) {
  console.error("Usage: tsx scripts/classify-ui-resource-preview.ts <image> [--fixture]");
  process.exit(1);
}

const abs = path.resolve(imgPath);
const outDir = path.join(process.cwd(), "nebulla-project", "ui-resource-catalog", "drafts");
fs.mkdirSync(outDir, { recursive: true });

const stub = {
  id: `draft-${path.basename(abs, path.extname(abs))}`.replace(/[^a-z0-9_-]+/gi, "-").toLowerCase(),
  kind: "figma_kit",
  platform: "web",
  page_types: ["dashboard"],
  density: "medium",
  personality: ["clean", "professional"],
  best_for: ["needs human review"],
  strengths: ["Auto-draft from vision script — validate before publish"],
  weaknesses: ["Unverified classification"],
  tags: ["draft", "vision"],
  description:
    "DRAFT profile generated by classify-ui-resource-preview.ts. Replace fields after manual review. Do not sync drafts to R2 until approved.",
  license: "unknown — review",
  source: `vision-draft:${path.basename(abs)}`,
  version: "0.0.0-draft",
  preview_local: fs.existsSync(abs) ? path.relative(process.cwd(), abs) : undefined,
  _meta: {
    status: "draft",
    note: "Human review required. Vision API enrichment not applied in fixture mode.",
  },
};

const apiKey =
  process.env.MAIN_API_KEY_GROK?.trim() ||
  process.env.OPENAI_API_KEY?.trim() ||
  process.env.ANTHROPIC_API_KEY?.trim() ||
  "";

if (!forceFixture && apiKey.length >= 20 && fs.existsSync(abs)) {
  console.log(
    "Vision API key present — v1 writes schema stub + instructions. Wire provider-specific vision call in a follow-up; refusing to invent unstructured output.",
  );
  stub._meta.note =
    "API key detected but vision call is intentionally stubbed until provider image payload is wired. Fill profile manually or re-run with refined prompt.";
} else if (!fs.existsSync(abs)) {
  console.warn(`Image not found (${abs}) — writing fixture draft only.`);
}

const outPath = path.join(outDir, `${stub.id}.json`);
fs.writeFileSync(outPath, `${JSON.stringify(stub, null, 2)}\n`, "utf8");
console.log(`Wrote draft: ${outPath}`);
console.log("Review → copy into profiles/ when approved. Never auto-publish drafts.");
