/**
 * Technical documentation Markdown export (Master Plan packaging).
 * Run: npm run test:tech-docs
 */
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  buildTechnicalDocumentationMarkdown,
  parsePagesFromSection4,
  sanitizePlanProseForExport,
  slugifyProjectForFilename,
  technicalDocumentationFilename,
} from "../lib/technicalDocumentationExport.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE_DIR = path.join(__dirname, "../nebula-project/fixtures/master-plan");

function loadFixture(name: string): Record<string, unknown> {
  return JSON.parse(fs.readFileSync(path.join(FIXTURE_DIR, name), "utf8")) as Record<
    string,
    unknown
  >;
}

const REQUIRED_HEADINGS = [
  "## Technical Documentation",
  "## Overview",
  "## System context",
  "## Architecture",
  "## Tech stack",
  "## Data",
  "## Key features",
  "## Application structure (pages / routes)",
  "## Security baseline",
  "## UI / UX direction",
  "## Operations",
];

console.log("good-crud-auth: required headings + pages");
{
  const plan = loadFixture("good-crud-auth.json");
  const result = buildTechnicalDocumentationMarkdown(plan, {
    projectName: "Agency Tasks",
    projectKey: "cfproj_test",
    generatedAt: "2026-08-05T12:00:00.000Z",
    hosting: {
      workspaceStorageMode: "dual",
      durableWorkspaceOk: true,
      hasR2Storage: true,
      syntheticIsolation: true,
    },
  });
  assert.match(result.filename, /agency-tasks-technical-documentation\.md$/);
  for (const h of REQUIRED_HEADINGS) {
    assert.ok(result.markdown.includes(h), `missing heading: ${h}`);
  }
  assert.ok(result.markdown.includes("Generated by Nebulla from Master Plan"));
  assert.ok(result.markdown.includes("/login"), "expected login route from §4");
  assert.ok(result.markdown.includes("Security baseline") || result.markdown.includes("Auth"));
  assert.ok(!result.markdown.includes("sk-"), "no sk- secrets");
  assert.ok(!/API_KEY\s*=/.test(result.markdown), "no API_KEY=");
}

console.log("thin-legacy: succeeds with Not specified; no invented routes");
{
  const plan = loadFixture("thin-legacy.json");
  const result = buildTechnicalDocumentationMarkdown(plan, {
    projectName: "Thin App",
    generatedAt: "2026-08-05T12:00:00.000Z",
  });
  assert.ok(result.markdown.includes("## Overview"));
  assert.ok(result.warnings?.length, "expect partial-plan warning");
  // Thin §4 has no concrete routes — Application structure must not invent e.g. /login
  const appStruct =
    result.markdown.split("\n## Application structure (pages / routes)\n")[1]?.split("\n## ")[0] ||
    "";
  assert.equal(
    (appStruct.match(/`\/[a-zA-Z]/g) || []).length,
    0,
    "thin plan Application structure should not invent backtick routes",
  );
  assert.ok(appStruct.includes("Home"), "expected Home page from thin §4 list");
}

console.log("empty plan: still exports");
{
  const result = buildTechnicalDocumentationMarkdown(
    {},
    { projectName: "Empty", generatedAt: "2026-08-05T12:00:00.000Z" },
  );
  assert.ok(result.markdown.includes("Not specified"));
  assert.equal(result.filename, "empty-technical-documentation.md");
}

console.log("sanitize + filename safety");
{
  const dirty = [
    "Stack: React",
    "API_KEY=sk-secretvaluehere123",
    "Use xai-abcdefghijklmnopqrstuv",
    "postgres://user:pass@host/db",
    "Normal line",
  ].join("\n");
  const clean = sanitizePlanProseForExport(dirty);
  assert.ok(!clean.includes("sk-secret"));
  assert.ok(!clean.includes("xai-abcdef"));
  assert.ok(!clean.includes("postgres://user:pass"));
  assert.ok(clean.includes("[redacted"));
  assert.ok(clean.includes("Normal line"));

  assert.equal(slugifyProjectForFilename("My Cool App!!!"), "my-cool-app");
  assert.equal(
    technicalDocumentationFilename({ projectName: "My Cool App" }),
    "my-cool-app-technical-documentation.md",
  );
  assert.equal(technicalDocumentationFilename({}), "technical-documentation.md");
}

console.log("parsePagesFromSection4: structured pages");
{
  const section4 = String(loadFixture("good-crud-auth.json")["4. Pages and navigation"]);
  const pages = parsePagesFromSection4(section4);
  assert.ok(pages.length >= 4, `expected several pages, got ${pages.length}`);
  assert.ok(pages.some((p) => p.route === "/login"));
  assert.ok(pages.some((p) => /purpose/i.test(p.purpose || "") || Boolean(p.purpose)));
}

console.log("secret context must not leak when only in excluded env-like lines");
{
  const plan = {
    "1. Goal of the app": "Demo app",
    "2. Tech and Research": "React + Postgres\nDATABASE_URL=postgres://u:p@h/db\nAPI_KEY=sk-abc1234567890",
    "3. Features and KPIs": "List items",
    "4. Pages and navigation": "Home",
    "5. UI/UX design": "Clean",
  };
  const result = buildTechnicalDocumentationMarkdown(plan, { projectName: "Secret Test" });
  assert.ok(!result.markdown.includes("postgres://u:p@"));
  assert.ok(!result.markdown.includes("sk-abc1234567890"));
  assert.ok(!/API_KEY\s*=\s*sk-/.test(result.markdown));
}

console.log("test-technical-documentation-export: ok");
